default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  #socket: /tmp/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ruby-ht-book-review-system_development

test:
  <<: *default
  database: ruby-ht-book-review-system_test

production:
  url: <%= ENV["DATABASE_URL"] %>
